### ISSUE TITLE
Can't resolve dependencies since CDI

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces-test#13]
I'm having this problem since I synced with the last version of primefaces-test, and I've tried with 2 different networks, same problem:

> [WARNING] The POM for org.apache.geronimo.specs:geronimo-jcdi_2.0_spec:jar:1.0.1 is missing, no dependency information available
> [WARNING] The POM for org.apache.geronimo.specs:geronimo-interceptor_1.2_spec:jar:1.0 is missing, no dependency information available
> [WARNING] The POM for org.apache.geronimo.specs:geronimo-annotation_1.3_spec:jar:1.0 is missing, no dependency information available
> [WARNING] The POM for javax.faces:jsf-api:jar:2.0 is missing, no dependency information available
> [WARNING] The POM for org.apache.openwebbeans:openwebbeans-impl:jar:2.0.5 is missing, no dependency information available
> [WARNING] The POM for org.apache.openwebbeans:openwebbeans-jsf:jar:2.0.5 is missing, no dependency information available
> [WARNING] The POM for org.apache.openwebbeans:openwebbeans-web:jar:2.0.5 is missing, no dependency information available
> [WARNING] The POM for org.apache.openwebbeans:openwebbeans-el22:jar:2.0.5 is missing, no dependency information available
>

**Comment by tandraschko** [comment]
It's available in central: http://search.maven.org/#artifactdetails%7Corg.apache.openwebbeans%7Copenwebbeans-impl%7C2.0.5%7Cjar

**Comment by Rapster** [comment]
Yep, I think it might be a problem with Eclipse. It works using command line...

**Comment by Rapster** [comment]
I managed to make the app run once... But I keep having this issue since I shutdown the server and executing a clean install... It seems having problem with `jsf-listener`. @tandraschko how do you "filter" this variable into web.xml? Is there any maven goal to execute?

> [WARNING] Could not instantiate listener ${jsf-listener}
> java.lang.ClassNotFoundException: ${jsf-listener}
>         at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
>         at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
>         at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
>         at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
>         at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:565)
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
>         at org.eclipse.jetty.server.handler.ContextHandler.loadClass(ContextHandler.java:1814)

**Comment by tandraschko** [comment]
jetty:run-exploded does the trick
