### ISSUE TITLE
f:selectItem itemLabel selected won't always be displayed in 'p:column h

### ISSUE THREAD

**Issue by NOTiFYcouk** [primefaces/primefaces-test#18]
I have created '<p:selectManyCheckbox id="carColumns" value="#{carService.selectedItems}"> as five versions of 'selectManyCheckbox' . 

Each of 'Year, Brand, Colour, Price, Sold' as 'f:selectItem itemLabel="xxxxx" itemValue="xxxxx"/> (see the five)

My 'p:dataTable' show each of the 'Year, Brand, Colour, Price, Sold' are five as:
CODE: SELECT ALL

<p:column headerText="Year" sortBy="#{car.year}" rendered="#{carService.yearColumnRendered}">
     <h:outputText value="#{car.year}"/>
 </p:column>
As each of the 'Year, Brand, Colour, Price, Sold' are selected (all the 100 for each) are displayed. If I then un-click one of the 'p:dataTable' then the list is removed. When I try to click the list of it won't show it again.

i.e Selected 'Brand', clicks it and in 'p:column headerText' and shows the 100 rows of 'Brand'. I un-click the 'Brands' they all disappear. When I click on ''Brand'' they are not shown this time.

[primefaces-test-master.zip](https://github.com/primefaces/primefaces-test/files/3441741/primefaces-test-master.zip)

**Comment by tandraschko** [comment]
This is just the issue tracker for the primefaces-test template, not for primefaces itself.
