### ISSUE TITLE
Dialog does not close in Chrome on touch devices

### ISSUE THREAD

**Issue by RalfScania** [primefaces/primefaces-test#19]
If you open a dialog through a button, link, etc. and try to close it by touching the close symbol in the top right, nothing happens. 
This was tested on Galaxy Tab and S10e. 

[primefaces-test-dialog.zip](https://github.com/primefaces/primefaces-test/files/3491617/primefaces-test-dialog.zip)

**Comment by tandraschko** [comment]
Please use the primefaces issue tracker, this is just the project template

**Comment by RalfScania** [comment]
Open in primefaces
