### ISSUE TITLE
ServletException upon clone / build

### ISSUE THREAD

**Issue by SkylerMime** [primefaces/primefaces-test#437]
When I clone this project, execute `mvn jetty:run`, and navigate to localhost:8080, the page does not render due to a ServletException:

```
[WARNING] handleException / java.io.IOException: jakarta.servlet.ServletException: /test.xhtml: The class 'org.primefaces.test.TestView' does not have the property 'string'.
```

I'm guessing this is because lombok is not correctly generating the getters and setters.

I am on macOS Sonoma 14.6.1

**Comment by melloware** [comment]
I have never seen this before but I just committed a fix if you want to try it.

**Comment by SkylerMime** [comment]
That fixed it, thanks :+1:
