### ISSUE TITLE
Cant enable JSF 2.3 features, mainly EL and CDI artifacts injection

### ISSUE THREAD

**Issue by erickdeoliveiraleal** [primefaces/primefaces-test#48]
I'm trying to use the code below to activate JSF 2.3 and exception  is thrown

> java.lang.RuntimeException: javax.faces.FacesException: Unable to find CDI BeanManager

 package org.primefaces.test;

import javax.faces.annotation.FacesConfig;
import javax.faces.annotation.FacesConfig.Version;

@FacesConfig(version = Version.JSF_2_3)
public class JSFConfigurator {
}

**Comment by melloware** [comment]
You don't need to do you? Simply run `mvn clean jetty:run -Pmyfaces23` or `mojarra23` to run JSF2.3 ?

**Comment by erickdeoliveiraleal** [comment]
I think @tandraschko can answer this.

**Comment by melloware** [comment]
Works fine for me? 
[jsf23.zip](https://github.com/primefaces/primefaces-test/files/5391080/jsf23.zip)

`mvn clean jetty:run -Pmyfaces23`
`mvn clean jetty:run -Pmojarra23`

I do not get the error you mention above when including your JSFConfigurator class.

**Comment by erickdeoliveiraleal** [comment]
@melloware sorry, the problem is when I also use the faces-config for JSF 2.3 and activate JSF 2.3 features
```
<?xml version="1.0" encoding="UTF-8"?>
<faces-config
    xmlns="http://xmlns.jcp.org/xml/ns/javaee"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee http://xmlns.jcp.org/xml/ns/javaee/web-facesconfig_2_3.xsd"
    version="2.3">
```

**Comment by melloware** [comment]
OK now I see it.

Works: `mvn clean jetty:run -Pmyfaces23`

Fails: `mvn clean jetty:run -Pmojarra23`

So it looks Mojarra related.

**Comment by erickdeoliveiraleal** [comment]
I tested in Tomcat and it's fine, it maybe some other lib that's causing it

**Comment by tandraschko** [comment]
in general a Mojarra thing: https://github.com/eclipse-ee4j/mojarra/issues/4642

You need to bind your BeanManager to java:comp/env/BeanManager, you can google about how to do it.
@melloware can you add this configs for OWB in the sample project here?

**Comment by melloware** [comment]
Yep will do it right now!

**Comment by melloware** [comment]
OK please review the PR.  It adds the BeanManager to Jetty JNDI and I verified Mojarra 2.3 now starts properly
