### ISSUE TITLE
Profile: Jakarta Faces 3.0

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces-test#56]
Add the ability to use Jakarta Faces 3.0 with profile `-Pjakarta30`.

**Comment by melloware** [comment]
Failing with:
```
 Could not find artifact jakarta.annotation:jakarta.annotation-api:jar:2.0.0
```

This is because Jakarta Faces relies on that annotations API but it is not in Maven Central:
https://search.maven.org/artifact/jakarta.annotation/jakarta.annotation-api

@GedMarc

**Comment by GedMarc** [comment]
Ya - there were... 4 of them (took the past weekend....)
No differences in the github code base between these versions and those specified (but it was really AAARRRGGGG when they did that!)

Here's the depedencyManagement I have for Jakarta IMPL- 

Think about hooking up to https://www.artifact-listener.org/ ;) helps me keep track of all this 

```
<dependency>
                <groupId>jakarta.activation</groupId>
                <artifactId>jakarta.activation-api</artifactId>
                <version>${jakarta.activation.version}</version>
            </dependency>
<dependency>
                <groupId>jakarta.enterprise</groupId>
                <artifactId>jakarta.enterprise.cdi-api</artifactId>
                <version>3.0.0</version>
            </dependency>
           <dependency>
                <groupId>jakarta.ejb</groupId>
                <artifactId>jakarta.ejb-api</artifactId>
                <version>4.0.0-RC2</version>
            </dependency>
<dependency>
                <groupId>jakarta.el</groupId>
                <artifactId>jakarta.el-api</artifactId>
                <version>4.0.0</version>
                <optional>true</optional>
            </dependency>
<dependency>
                <groupId>org.glassfish</groupId>
                <artifactId>jakarta.el</artifactId>
                <version>4.0.0</version>
                <optional>true</optional>
            </dependency>
<dependency>
                <groupId>jakarta.transaction</groupId>
                <artifactId>jakarta.transaction-api</artifactId>
                <version>2.0.0-RC3</version>
            </dependency>
<dependency>
                <groupId>jakarta.websocket</groupId>
                <artifactId>jakarta.websocket-api</artifactId>
                <version>2.0.0-RC1</version>
            </dependency>
 <dependency>
                <groupId>jakarta.faces</groupId>
                <artifactId>jakarta.faces-api</artifactId>
                <version>3.0.0</version>
            </dependency>

            <dependency>
                <groupId>jakarta.json</groupId>
                <artifactId>jakarta.json-api</artifactId>
                <version>2.0.0</version>
            </dependency>

            <dependency>
                <groupId>org.glassfish</groupId>
                <artifactId>jakarta.faces</artifactId>
                <version>3.0.0</version>
            </dependency>

            <dependency>
                <groupId>jakarta.interceptor</groupId>
                <artifactId>jakarta.interceptor-api</artifactId>
                <version>1.2.5</version>
            </dependency>

            <dependency>
                <groupId>org.glassfish.web</groupId>
                <artifactId>jakarta.servlet.jsp</artifactId>
                <version>2.3.6</version>
            </dependency>

            <dependency>
                <groupId>org.glassfish.web</groupId>
                <artifactId>javax.servlet.jsp.jstl</artifactId>
                <version>1.2.5</version>
            </dependency>

            <dependency>
                <groupId>jakarta.servlet.jsp.jstl</groupId>
                <artifactId>jakarta.servlet.jsp.jstl-api</artifactId>
                <version>2.0.0-RC1</version>
            </dependency>
```

**Comment by GedMarc** [comment]
```
<dependency>
                <groupId>jakarta.validation</groupId>
                <artifactId>jakarta.validation-api</artifactId>
                <version>3.0.0</version>
            </dependency>
```

**Comment by melloware** [comment]
Also having an issue with:
```
Could not find artifact org.primefaces:primefaces:jar:9.0-SNAPSHOT-jakarta
```
**pom.xml**
```xml
                <dependency>
                    <groupId>org.primefaces</groupId>
                    <artifactId>primefaces</artifactId>
                    <version>9.0-SNAPSHOT-jakarta</version>
                </dependency>
```

Because it looks like there is only 1 Maven .pom file for both JARS?
![image](https://user-images.githubusercontent.com/4399574/97902072-0f17dd00-1d0b-11eb-9517-3bbb3c74dd92.png)

**Comment by GedMarc** [comment]
should work as a classifier 👍 

so version 9.0-SNAPSHOT
&lt;classifier&gt; jakarta

**Comment by GedMarc** [comment]
shouldn't need but in case - JAXB
```
 <dependency>
                <groupId>jakarta.xml.bind</groupId>
                <artifactId>jakarta.xml.bind-api</artifactId>
                <version>3.0.0-RC3</version>
                <exclusions>
                    <exclusion>
                        <artifactId>jakarta.activation-api</artifactId>
                        <groupId>jakarta.activation</groupId>
                    </exclusion>
                </exclusions>
                <optional>true</optional>
            </dependency>

            <dependency>
                <groupId>org.glassfish.jaxb</groupId>
                <artifactId>jaxb-runtime</artifactId>
                <version>2.3.3</version>
            </dependency>
```

**Comment by melloware** [comment]
I think I got it trying something now.

**Comment by melloware** [comment]
OK I got the right annotation 2.0.0 to download by adding this:
```xml
        <repository>
            <id>Jakarta</id>
            <url>https://jakarta.oss.sonatype.org/content/groups/staging/</url>
        </repository>
```

But the bigger problem is with things like OpenWebBeans that we are using for CDI it has all the javax. interfaces so we would need an OpenWebBeans that supported the jakarta interfaces instead of javax right?  This cascades all the way through?

**Comment by GedMarc** [comment]
The only issue I've found so far with a shade is annotation processing, where the service loader file javax.annotation.processor gets renamed to jakarta.annotation by mistake, easily avoided when it pops up
Otherwise everything seems to shade great :- (They have released an eclipse plugin btw that does the exact shade as well)

Creating the hierarchy with javax. to jakarta - That's exactly what I did, I didn't try with jetty,  - I threw it onto Servlet 5, Undertow and Guice as the DI while the platforms catchup - I don't like CDI so much :)

Thanks for that fix!!!! That is so much better!!!!!

**Comment by GedMarc** [comment]
(https://github.com/GedMarc/GuicedEE-Examples/tree/master/Faces)

**Comment by tandraschko** [comment]
let me do it tomorrow ;)

**Comment by tandraschko** [comment]
is there even a jetty plugin which supports jakarta yet?

everything else should be no problem

**Comment by tandraschko** [comment]
https://github.com/eclipse/jetty.project/issues/4578#issuecomment-588142074

**Comment by GedMarc** [comment]
tomcat as well : https://github.com/apache/tomcat-jakartaee-migration

**Comment by melloware** [comment]
For this PF test project I think we only care about Jetty for now

**Comment by tandraschko** [comment]
dont have much time right now but something similiar should work:
https://gist.github.com/tandraschko/e767e8793d4b6d03275a0171af8f0fcc

NOTE: this requires jakarta or javax packages in compile and you always need to activate it via: -Pjakarta or -Pjavax

so -Pjakarta currently only works with myfaces30 and actually needs:
-Pjakarta,myfaces30
or
-Pjavax,myfaces23

but somehow jetty start fails, no time to check it in detail, just my short ideas

**Comment by tandraschko** [comment]
it might just be a jetty problem, maybe you can run the WAR generated by "clean package -Pjakarta,myfaces30" in a Tomcat10, it should work.

**Comment by tandraschko** [comment]
ok, web.xml needs also be aligned with jakarta

maybe its better to have a jakarta branch

**Comment by melloware** [comment]
Yeah Jetty has issues because of our JNDI fix for BeanManager with javax. etc,  However I do think there is still a problem with Jetty plugin looking for javax.servlet explicityly...

```
java.lang.NoClassDefFoundError: javax/servlet/ServletContextListener
    at java.lang.ClassLoader.defineClass1 (Native Method)
    at java.lang.ClassLoader.defineClass (ClassLoader.java:1016)
    at java.security.SecureClassLoader.defineClass (SecureClassLoader.java:174)
    at java.net.URLClassLoader.defineClass (URLClassLoader.java:550)
    at java.net.URLClassLoader$1.run (URLClassLoader.java:458)
    at java.net.URLClassLoader$1.run (URLClassLoader.java:452)
    at java.security.AccessController.doPrivileged (Native Method)
    at java.net.URLClassLoader.findClass (URLClassLoader.java:451)
    at org.eclipse.jetty.webapp.WebAppClassLoader.foundClass (WebAppClassLoader.java:607)
```

**Comment by melloware** [comment]
+1 on the branch idea as this is too messy with profiles.

**Comment by christophs78** [comment]
I'm currently looking into this.

**Comment by tandraschko** [comment]
the jakarta branch works fine for me, i will close this
