### ISSUE TITLE
Make JSF "provided"

### ISSUE THREAD

**Issue by vernetto** [primefaces/primefaces-test#8]
Deploying to Wildfly, I was getting this error:
The tag named inputFile from namespace http://xmlns.jcp.org/jsf/html has a null handler-class defined

and it went away when I added  scope provided for the org.glassfish:javax.faces:2.2.7 dependency

**Comment by tandraschko** [comment]
The PF team is using jetty
As this test project is for replicating issue for the PF team -> won't fix.
